server:
  port: 9000
#  servlet:
#    context-path: /
#    encoding:
#      charset: utf-8
#      enabled: true

spring:
  config:
    import:
      - application-aws.yml

  application:
    name : swith

  datasource:
    #    platform: mysql
    #    url: jdbc:mysql://localhost:3306/test3?serverTimezone=Asia/Seoul
    #    username: root
    #    password: smilechs5542
    #    platform: mysql
    url: jdbc:h2:tcp://localhost/~/querydsl
    # ENC(tlzBhvJGBqVCdhlED4A3+8bI1XsUL7LLkJqqqie5QwmbLWPKill6zYU04E0ZOMpdGs7Y+O5ho9t3aBVRojNDd3jxlLE7pIkZZu7Cr2W/qre0XpWHMZH2PA==)
    # jdbc:mysql://localhost:3306/test_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sa # ENC(EWZbD80PyOIlDT2TjHmxbiicPlktenKz)
    password:    # ENC(psGvp3CI0mqxpQT5nD3E7h0klqGCia0c)
    driver-class-name: org.h2.Driver # mysql 8버전
  #    hikari:
  #      connectionInitSql: "SET NAMES 'utf8mb4'"
  #      leak-detection-threshold: 2000



  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update # create, update, none
      naming:
        #entity만들때, 변수명 그대로 데이터베이스 필드에 넣어주겠다.
        #만약, org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy 전략을 사용하겠다고 하면,
        #entity에서 변수명을 myEmail 이라고 하면, DB에 myEmail이 아닌 my_email로 만들어짐.
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false #jpa 기본 numbering 전략을 따라가지 않겠다.
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true #querydsl jpql 보기


  security:
    user:
      name: test
      password: 1234

  oauth2:
    client:
      registration:
        facebook:
          client-id: ENC(IscomAi+P52awf3dhXmeBFBbc/FqK30P)
          client-secret: ENC(Qg7XhLb+yIVr6GcBu99Ljuk7+i8ZubyXWrc205FMohnoiaeZijnqC0Jw7YfVSaGm)
          scope:
            - public_profile
            - email

#logging:
#  level:
#    org.hibernate.SQL: debug # 하이버네이트가 생성하는 SQL이 다보인다.
##    org.hibernate.type:  #binding parameter의 값이 무엇인지를 알려줌.



secret:
  # private-diary-key: ${PRIVATE_DIARY_KEY}
  jwt-secret-key: ENC(j9LQ4c0yOt4FTCPsqjnjpFDarB+xQ0xNkdYP9KM8POD2EqlzIcZnEHqZ4RBs4DYx+fp2PwvGfi4HVMgrvNuUhqSf+h2uexUSHRLXsUB6t7NwBmJ2BgITYCtWeDQn6tkYVRR8hh9cZ1g8Z5fEs9hd4g==)


file:
  path:

jasypt:
  password: ${PASSWORD}